name: zgalea_lake
config-version: 2
profile: local
require-dbt-version: ">=1.7.0"

model-paths: [ "models" ]

models:
  +file_format: hudi
  zgalea_lake:
    marts:
      +materialized: table
    raw:
      +materialized: view
    hub:
      +materialized: table