name: zgalea_lake
config-version: 2
profile: local
require-dbt-version: ">=1.7.0"

model-paths: [ "models" ]
models:
  # Carpeta para modelos marts
  marts:
    +materialized: table

  # Carpeta para modelos raw
  raw:
    +materialized: view

  # Carpeta para modelos hub
  hub:
    +materialized: table