version: '3'
services:
  dbt_spark:
    build:
      context: ./dbt
      dockerfile: Dockerfile
    volumes:
      - ./data:/data

  binance_scrapping:
    build:
      context: extractors/binance
      dockerfile: Dockerfile
    volumes:
      - ./data:/data

  elementary:
    build:
      context: ./elementary
      dockerfile: Dockerfile
    command: report
    volumes:
      - ./dbt:/usr/app
      - ./dbt/.dbt/:/root/.dbt/
  
  selenium-docker:
    image: seleniarm/standalone-chromium:latest
    container_name: selenium-docker
    platform: linux/amd64
    ports:
      - "4444:4444"
      - "5900:5900"
      - "7900:7900"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./selenium/config.toml:/opt/bin/config.toml
      - ./selenium/assets:/opt/selenium/assets
