version: '3'
services:
  dbt_spark:
    build:
      context: ./dbt
      dockerfile: Dockerfile
    volumes:
      - ./data:/data

  twitter_extractor:
    build:
      context: ./extractors/twitter
      dockerfile: Dockerfile
    volumes:
      - ./data:/data

  elementary:
    build:
      context: ./elementary
      dockerfile: Dockerfile
    command: report
    volumes:
      - ./dbt:/usr/app
      - ./dbt/.dbt/:/root/.dbt/
