version: '3'
services:
  dbt_spark:
    build:
      context: ./dbt
      dockerfile: Dockerfile
    volumes:
      - ./data:/data

  binance-scrapper:
    build:
      context: extractors/binance
      dockerfile: Dockerfile
    volumes:
      - ./data:/data

  elementary:
    build:
      context: dbt/elementary
      dockerfile: Dockerfile
    command: report
    volumes:
      - ./dbt:/usr/app
      - ./dbt/.dbt/:/root/.dbt/
  
  spark3-thrift:
    build: thrift/
    ports:
      - "10000:10000"
      - "4040:4040"
    command: >
      --packages org.apache.hudi:hudi-spark3.3.x_2.12:1.0.0-beta1
      --conf 'spark.serializer=org.apache.spark.serializer.KryoSerializer'
      --conf 'spark.sql.hive.convertMetastoreParquet=false'
      --class org.apache.spark.sql.hive.thriftserver.HiveThriftServer2
      --name "Thrift JDBC/ODBC Server"
    volumes:
      - ./data/:/spark-warehouse/
      - ./thrift/spark-defaults.conf:/usr/spark/conf/spark-defaults.conf
