version: '3'
services:
  dbt_spark:
    build:
      context: ./dbt
      dockerfile: Dockerfile
    volumes:
      - ./data:/data

  binance-scrapper:
    build:
      context: extractors/binance
      dockerfile: Dockerfile
    volumes:
      - ./data:/data

  elementary:
    build:
      context: dbt/elementary
      dockerfile: Dockerfile
    command: report
    volumes:
      - ./dbt:/usr/app
      - ./dbt/.dbt/:/root/.dbt/
  
  spark3-thrift:
    build: thrift/
    ports:
      - "10000:10000"
      - "4040:4040"
    depends_on:
      - hive-metastore
    command: >
      --class org.apache.spark.sql.hive.thriftserver.HiveThriftServer2
      --name Thrift JDBC/ODBC Server
    volumes:
      - ./data/:/spark-warehouse/
      - ./thrift/hive-site.xml:/usr/spark/conf/hive-site.xml
      - ./thrift/spark-defaults.conf:/usr/spark/conf/spark-defaults.conf
    environment:
      - WAIT_FOR=hive-metastore:5432
        
        
  hive-metastore:
    image: postgres:9-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./.hive-metastore/:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=usuario
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=metastore
