local:
  target: dev
  outputs:
    dev:
      type: spark
      method: thrift
      schema: default
      host: spark3-thrift
      port: 10000

elementary:
  target: dev
  outputs:
    dev:
      type: spark
      method: thrift
      schema: default
      host: spark3-thrift
      port: 10000